name: Build and Release OnePlus Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a release?'
        required: true
        type: boolean
        default: false
      ksun_branch:
        description: "Choose KernelSU Next Branch"
        required: true
        type: choice
        options:
          - stable
          - next
        default: stable

jobs:
  build-batch-1:
    name: build-batch-1 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ inputs.ksun_branch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP12r
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_12r_v.xml
            android_version: android13
            kernel_version: "5.15"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      ksun_branch: ${{ inputs.ksun_branch }}

  build-batch-2:
    name: build-batch-2 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ inputs.ksun_branch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP13
            soc: sun
            branch: oneplus/sm8750
            manifest: oneplus_13.xml
            android_version: android15
            kernel_version: "6.6"
          - model: OP13r
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_13r.xml
            android_version: android14
            kernel_version: "6.1"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      ksun_branch: ${{ inputs.ksun_branch }}

  trigger-release:
    needs:
      - build-batch-1
      - build-batch-2
    runs-on: ubuntu-latest
    if: ${{ inputs.make_release }}
    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: "OnePlus Kernels With KernelSU Next (${{ inputs.ksun_branch }}) & SUSFS v1.5.7"
      RELEASE_NOTES: |
        This is a test build of OnePlus kernels with KernelSU Next and SUSFS v1.5.7.
        - Supported devices: OP12r, OP13, OP13r
        - KernelSU branch: ${{ inputs.ksun_branch }}
        - For issues, please report to the repository.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate and Create New Tag
        run: |
          BASE_TAG="v1.5.7-r0"
          LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name' || echo "")
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="$BASE_TAG"
          fi
          if [[ ! "$LATEST_TAG" =~ ^v1\.5\.7-r[0-9]+$ ]] && [ "$LATEST_TAG" != "v1.5.7-r0" ]; then
            echo "Invalid tag format: $LATEST_TAG"
            exit 1
          fi
          NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: true
          name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_NOTES }}
          files: |
            ./downloaded-artifacts/kernel-*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
